cart/urls.py
from django.urls import reverse
from django.urls import path
from . import views

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('addtocart/<int:id>/', views.addtocart, name='addtocart'),
    path('delete_cart_item/<int:id>', views.delete_cart_item, name='delete_cart_item'),
    # path('checkout/', views.checkout_form, name='checkout'),
]

racemtriki/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('users.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from store.models import Product
# from users.models import Profile

# Create your models here.

class Cart(models.Model):
	total_products = models.IntegerField(default=0)
	total_amount = models.IntegerField(default=0)
	date_orderd = models.DateTimeField(auto_now=True)

	def __str__(self):
	    return str(self.id)


class CartItem(models.Model):
	cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
	size = models.CharField(max_length=30, null=True, default=None)
	time_added = models.DateTimeField(auto_now=True, blank=True, null=True)
	quantity = models.IntegerField(default=1)
	total_cost = models.IntegerField(default=0)

	def __str__(self):
	    return str(f'{self.product.title} - {self.cart}')

cart/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Cart, CartItem
from store.models import Product
from users.models import Account
from datetime import datetime
# Create your views here.

def cart(request):

	# request.session.set_expiry(3)
	request.session.set_expiry(86400)
	try:
		cart_id = request.session['cart_id']
	
	except:
		cart_id = None

	if cart_id:
		
		if request.session['total_products'] == 0:
			context = {'empty': True}

		else:
			cart = Cart.objects.get(id = cart_id)
			context = {'cart': cart}

	else:
		context = {'empty': True}

	return render(request, 'cart/cart.html', context)


def addtocart(request, id):
	# person = Account.objects.get(username=request.user.username)
	size = request.GET.get('size')

	try:
	    cart_id = request.session['cart_id']
	except:
	    new_cart = Cart()
	    new_cart.save()
	    request.session['cart_id'] = new_cart.id
	    cart_id = new_cart.id

	cart = Cart.objects.get(pk = cart_id)

	product = Product.objects.get(pk = id)

	try:
		cartitem = CartItem.objects.get(cart=cart, product=product, size=size)
		cartitem.quantity += 1
		cartitem.total_cost += product.price
		cart.total_products += 1

	except:
		cartitem = CartItem(
					cart = cart,
					product = product,
					total_cost = product.price,
					size = size,
				)
		cart.total_products += 1
	cartitem.save()

	# cart.cart_item.add(cartitem)
	cart.total_amount += cartitem.product.price
	cart.save()
	request.session['total_products'] = cart.total_products

	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
	# return redirect('cart')

def delete_cart_item(request, id):
	cart_id = request.session['cart_id']
	cart = Cart.objects.get(pk = cart_id)
	cartitem = CartItem.objects.get(pk=id)
	print(cartitem.quantity)
	cart.total_products -= cartitem.quantity
	cart.total_amount -= cartitem.total_cost
	request.session['total_products'] -= cartitem.quantity
	cartitem.delete()
	cart.save()

	return redirect('cart')

cart/templates/cart/cart.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}

<div class="cart">
    <h4 class="font-weight-bold text-center">VOTRE PANIER</h4>
    {% if empty %}
    <div class="card cart-card mt-2 mb-3">
        <div class="card-body">
            <div class="">
                <a href="{% url 'home' %}">
                    <button class="link-btn-cart btn btn-sm"> &#8676;</button>
                </a>
            </div>
            <hr>
            <h1 class="textcen">Votre panier est vide, veuillez continuer vos achats.</h1>
        </div>
    </div>
    {% else %}
    <div class="card cart-card mt-2">
        <div class="card-body">
            <div class="">
                <a href="{% url 'home' %}">
                    <button class="link-btn-cart btn btn-sm">Continuer vos achats &#8676;</button>
                </a>
            </div>
            <hr>
            <div class="row">
                <div class="col-3">Articles:<strong>{{ cart.total_products }}</strong></div>
                <div class="col-3">Le total:<strong>{{ cart.total_amount }}</strong></div>
                <div class="col-6">
                    <a href="{% url 'checkout' %}"><button class="btn btn-sm btn-success float-right">la caisse</button></a>
                </div>
            </div>
        </div>
    </div>
    <div class="card cart-card mt-3 mb-3">
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Sr. #</th>
                        <th>Produit</th>
                        <th>Prix</th>
                        <th>Size</th>
                        <th>Quantité</th>
                        <th>Total</th>
                        <th>Choix</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart.cartitem_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><img class="cart-image" src="{{ item.product.image.url }}"></td>
                        <td>{{ item.product.price }}</td>
                        <td>{{ item.size }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.total_cost }}</td>
                        <td>
                            <a href="{% url 'delete_cart_item' item.id %}">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}